### /api/create-payment-intent
POST http://localhost:3000/api/create-payment-intent HTTP/1.1
Content-Type: application/json

{
  "amount": 1000
}


###
POST http://localhost:3000/api/graphql
Content-Type: application/json

{
  "query": "query Categories {\n  categories {\n    items {\n      name\n      price\n    }\n  }\n}",
  "variables": {},
  "operationName": "Categories"
}

###
GET http://localhost:3000/api/health

###
GET http://localhost:3000/api/graphql?query=%7B__typename%7D

###
GET http://localhost:3000/api/graphql?query=%7B__typename%7D
apollo-require-preflight: true

### post user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "id": "2",
  "email": "test2@test.com",
  "password": "my password 4321"
}

### get user by ID
GET http://localhost:3000/api/users/2

### get user by email
GET http://localhost:3000/api/users?email=test@test.com

### post note
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "userId": "3",
  "title": "note 3 title",
  "body": "Hello World"
}

### update note
POST http://localhost:3000/api/notes/2
Content-Type: application/json

{
  "title": "note 1 title updated",
  "body": "updated body"
}

### get notes by user ID
GET http://localhost:3000/api/notes?userId=1

### get note by ID
GET http://localhost:3000/api/notes/0

### delete note by ID
DELETE http://localhost:3000/api/notes/2